DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS(
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME    VARCHAR(20) UNIQUE NOT NULL,
    PASSWD      VARCHAR(32) NOT NULL
);

INSERT INTO USERS (USERNAME, PASSWD) VALUES
    ("alice", MD5 ("alice123")),
    ("bob", MD5 ("bob123"));